require "saiprasad.options"
require "saiprasad.keymaps"
require "saiprasad.plugins"
require "saiprasad.cmp"
require "saiprasad.lsp"
vim.cmd "colorscheme solarized8_high"
require "saiprasad.treesitter"
require "saiprasad.autopairs"
require "saiprasad.comment"
require "saiprasad.lualine"
require "saiprasad.nvim-tree"
require "saiprasad.bufferline"
require "saiprasad.null-ls"
